version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./dist:/usr/share/nginx/html/dist
            - ./app/html:/usr/share/nginx/html/html
            - ./app/src:/usr/share/nginx/html/src
            - ./docker/nginx/${NGINX_CONF}:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
    gulp:
        depends_on:
            - nginx
        build:
            context: .
            dockerfile: docker/gulp/Dockerfile
        command:
            - gulp
        ports:
            - '3000:3000'
            - '3001:3001'
        volumes:
            - ./app:/application/app
            - ./dist:/application/dist
